### ISSUE TITLE
Change `website` to `url`

### ISSUE THREAD

**Issue by dbkaplun** [jsonresume/resume-schema#148]

**Comment by DandyDev** [comment]
+1

**Comment by opensourcegrrrl** [comment]
bump @thomasdavis

**Comment by olivif** [comment]
+1 

shall we merge? :)

**Comment by chrisdotcode** [comment]
I'm indifferent to this - and I don't mind merging it, but can someone give me reason as to why they prefer 'url'?

**Comment by stp-ip** [comment]
A url could point to a resource, an app or similar, it does not need to be a website. In addition to that it makes all urls consistently with naming them url.
(as a sidenote: bibJSON uses "source")

**Comment by chrisdotcode** [comment]
Sounds good. We'll merge this when we can.

**Comment by aloisdg** [comment]
Sorry, to add a new comment. Just to say that I think about @stp-ip sidenote and I really like it. It will add more cohesion with bibjson. I feel that  it is more "human-compliant". 

[bibjson spec](http://wiki.okfn.org/Projects/openbibliography/bibjson/schema/v0.82):

```
"source": {
         "description": "The URL where the collection file was uploaded from, if there is one",
         "format": "url",
         "type": "string"
       },
```

Since every body seems agree with URL. I think we should keep it for the current version, but , at least, keep this idea for the next one.

**Comment by olivif** [comment]
@aloisdg hmm, interesting. I do like it. Let's re-open and rename the issue to url -> source so we don't forget :smile:

**Comment by aloisdg** [comment]
Glad you like it too :smile: By the way, the new title shouldn't be "How to rename website?"

Call an url "url" is like called a string "string",  isn't it?

**Comment by olivif** [comment]
@aloisdg I think there was a PR for this which already got merged in, so the property is called Url now (used to be website). That's why "Change url to (bibJSON) source" made sense to me :smile:

**Comment by aloisdg** [comment]
@olivif The conversation was created for an older version. I think that we should read it straight. With the current title, it seems that the fourth first commenters agree with the switch to "source". Thats not right.

**Comment by olivif** [comment]
@aloisdg yeah I agree, it's confusing. maybe we should create a new issue instead of reusing this? :smile:

**Comment by stp-ip** [comment]
It's a different issue in my opinion. Most likely 2-3:
* Use source instead of url to be similar to bibjson
* Use source instead of url for all occurances (I would probably dislike that. As a website is not really the source.)

Closing as the old issue is done and anything else should start with a clean issue.
