### ISSUE TITLE
Skill levels should have pre-defined values.

### ISSUE THREAD

**Issue by buraksarica** [jsonresume/resume-schema#16]
So that resumes would easily be filtered.

**Comment by stp-ip** [comment]
Using a predefined number for each level and then make the different levels defaults, but customizable would solve most of the issues in my opinion. What does the rest think?
```
"level": {
    "enum": [
        {"0": null},
        {"1": "beginner"},
        {"2": "competent"},
        {"3": "advanced"},
        {"4": "expert"}
    ],
    "default": "0"
}
```

**Comment by opensourcegrrrl** [comment]
+1 for "mwaclawek commented on Jul 13, 2014".

**Comment by aloisdg** [comment]
Is `null`really needed? If you have a skill at the level `null`, why bother writing it in th resume?

**Comment by opensourcegrrrl** [comment]
@mwaclawek correct me if this is inaccurate, `null` does not mean that that person's skill are "null"; it means that they decline to disclose the level for some reason.

**Comment by stp-ip** [comment]
@aloisdg @opensourcegrrrl I would say that null is just a not disclosed skill level. Could be used as defaults for themes, as placesholder in editors etc..

**Comment by aloisdg** [comment]
I understand more now. Therefore, I think the default placeholder should be beginner, but this is not a concern for the spec. Thank you :)

**Comment by stp-ip** [comment]
@aloisdg I would say beginner as default could be wrong. Imagine someone just not disclosing any level for all their skills. This would lead for them to be a beginner in all of them instead of them just being no skill level at all for that skill.

**Comment by aloisdg** [comment]
@stp-ip you are right.

**Comment by opensourcegrrrl** [comment]
-1 for beginner for being the default for reasons in my previous comment.

**Comment by aloisdg** [comment]
-1 too (is it matter?)

**Comment by stp-ip** [comment]
Just to revisit the whole discussion with m own point of view.
* numerical values make it more subjective
* predefined levels are bad for i18n
* predefined levels make it easier for all participants

Therefore I think we should go for predefined values as @mwaclawek suggested:
```
"level": {
    "enum": [
        null,
        "beginner",
        "competent",
        "advanced",
        "expert"
    ],
    "default": null
}
```
How to solve i18n with predefined values is not just needed here, but in other places too. So we need a solution anyway. Reducing the ease of the schema seems imperfect.

**Comment by aloisdg** [comment]
Can we use "early" too.

I use and read Python sometimes. I never release a project with this techno. I am an early dev.
I just start to learn F#. I would love to use it more. I am a beginner dev.

> What I propose is we have beginning coders and early coders. I got this idea from a painting teacher who kept referring to students who had never painted as “beginners”, but those who had painted for about one class as “early”. 

[Early vs. Beginning Coders](http://zedshaw.com/2015/06/16/early-vs-beginning-coders/) by @zedshaw

**Comment by olivif** [comment]
Let me give a counter-example to the levels. There are people who have very specific skills that might not fit into the enum above. Or rather, they would fit, but they would not mean as much as a different keyword would, that is specific to that skill.

Wine tasting professionals for instance 

```
skills: [
    {
        name: "Sommelier",
        level: "Level 1"
    }   
]
```
I would much prefer what @mwaclawek said here 

>Maybe the skill level should rather be a plain string as well, allowing the user to describe themselves in their own words, and giving "beginner", "advanced" and "expert" as examples in the description.

I think we are losing some flexibility with the enum and it is not really clear to me what we are gaining. If the goal is to make it easy for people to fill in the resume, I think having the levels as an example in the description should be sufficient, as opposed to enforcing it in the schema. I am willing to be convinced otherwise though :smile:

**Comment by opensourcegrrrl** [comment]
Another counter example from my own human-language skill levels:

English Native
Finnish C1
Spanish C1
German B2
Mandarin A2
Hungarian A2

The levels are defined per https://en.wikipedia.org/wiki/Common_European_Framework_of_Reference_for_Languages.

These levels would never apply to programming languages.

**Comment by aloisdg** [comment]
> I think we are losing some flexibility with the enum and it is not really clear to me what we are gaining.

We loose flexibility for coherence. (It is not necessarily good)

Imagine a HR who want to look in a database for every employees who has a level in "skill name" where "skill level" is superior than "enum value".

With a blank string, it will be difficult to parse, isnt?

**Comment by aloisdg** [comment]
@opensourcegrrrl We have [`languages`](https://github.com/jsonresume/resume-schema/blob/master/resume.json#L109) for this case. We could remove it and use skills for languages, but I dont really like this idea.

**Comment by opensourcegrrrl** [comment]
@aloisdg Thanks, got it.

**Comment by stp-ip** [comment]
A few possibilities:
* predefined levels (less subjective, machine readable, inflexible)
* numeric levels (subjective, machine readable, flexible)
* numeric levels + string level (subjective, machine readable, flexible)
* string level (subjective, flexible)

I vote for either predefined or numeric + string level. Machine readable/search-able is something I find quite valuable.

**Comment by aloisdg** [comment]
@stp-ip I prefer a predefined levels. It feels clearer and easier.

By the way a predifined level can be easily convert to a percent or anything if you really want. I dislike percent because it allows to use more sub level without clear mining.

| label | star | % |
| ----- | ----- | ------ |
| beginner | ★☆☆☆☆ | 20% |
| early | ★★☆☆☆ | 40% |
| competent | ★★★☆☆ | 60% |
| advanced | ★★★★☆ | 80% |
| expert | ★★★★★ | 100% |

**Comment by chrisdotcode** [comment]
So, guys, an enum or a free-form string is winning simply because we like machine readability.

10% is not quantifiable (10% of what?), whereas "beginner" certainly is. Now, it is true that constitutes a beginner is [highly subjective](https://en.wikipedia.org/wiki/Dunning%E2%80%93Kruger_effect), but an enum *IS* machine readable, and most people are comfortable and can honestly rate their skill level on a beginner - expert spectrum far more easily than any alternative.

Failing that, we forgo any attempts at being machine readable, and go full-subjective with a text field.

I personally think an enum is the way to go, and the "hard part" about that is choosing what we call the levels.

**Comment by chrisdotcode** [comment]
I really like @aloisdg's quantifications of the skill levels, and if we choose this route (I think "beginner" and "early" (and "advanced" and "expert") are the same thing, though),  we aught to document those descriptions somewhere.

As a matter of fact, even if we don't quite agree on what to call the fields, if we can agree on the descriptions of the levels, then that's all we need - because we have now semantically specified skill level. That being said, I don't 100% agree with @aloisdg's level descriptions either, but it's a fantastic start.

**Comment by aloisdg** [comment]
@chrisdotcode Thank you! Feel Free to change it. If you want to know more about the difference between beginnner and early : [Early vs. Beginning Coders](http://zedshaw.com/2015/06/16/early-vs-beginning-coders/) by @zedshaw.

**Comment by stp-ip** [comment]
My proposal would be to have defined levels within our documentation as @aloisdg provided:

| level | label | star | n% | Closing an issue with this skill
| --- | --- | --- | --- | --- |
| 0 | null | not provided | not provided | not provided | No level was provided
| 1 | beginner | ★☆☆☆☆ | 20% | I will teach you how to do it
| 2 | early | ★★☆☆☆ | 40% | I will help you to do it
| 3 | competent | ★★★☆☆ | 60% | I will follow how you do it
| 4 | advanced | ★★★★☆ | 80% | I will be there in case of trouble
| 5 | expert | ★★★★★ | 100% | I will be there when it is ready

This way we could make it machine readable and possible to localize.
We would have something like the following within a resume: 

skills: [
    {
        name: "Sommelier",
        level: "1",
        label: "beginner"
    }   
]

In the schema itself we could have the level be an enum from 0-5 and label and name would be a string.

I would love to decide on this slowly, so we can move it into a PR needed state.

**Comment by aloisdg** [comment]
Some points:

* The level as label is enough. I dont think we need more than the enum.
* `Closing an issue with this skill` is here as an idea, nothing fixed.
* Should we use "null" or "undefined"?

**Comment by stp-ip** [comment]
So your suggestion would be:

```
skills: [
    {
        name: "Sommelier",
        level: "beginner",
        label: "Anfänger"
    }   
]
```
> "Closing an issue with this skill" is here as an idea, nothing fixed.
The idea is nice and we can easily refine it even after v1 as it's mainly documentation.

> Should we use null or undefined?
```null``` vs ```undefined``` needs more input from others I think: @chrisdotcode @olivif

**Comment by opensourcegrrrl** [comment]
@stp-ip How about instead of `null` or `undefined` it is `unprovided`?

**Comment by stp-ip** [comment]
@opensourcegrrrl seems this would be the most generic and non language (JSON, YAML) specific.
+1 for ```unprovided```

**Comment by olivif** [comment]
@opensourcegrrrl I like `unprovided`.

@stp-ip I like your table and I think this is a good trade-off between flexibility and machine readability. This solves my counter example while it's easy for theme creators to use and machines to aggregate on. 

What I am concerned about with this example is that you can provide consistent information, like so. 

```
skills: [
    {
        name: "Sommelier",
        level: "1",
        label: "advanced"
    }   
]
```
But it's not a deal breaker, we can have custom validation for this if needed. Or we can even allow users to set one of the fields (level for instance), and we auto generate the others.

**Comment by aloisdg** [comment]
> you can provide consistent information

inconsistent I guess ;)

I think we should remove the number level and  rename `label` as `level`.

**Comment by stp-ip** [comment]
Without label, we would remove the possibility to localize.
I am alright with having the level be an enum with the standard levels instead of a numerical one, but I think a label, even if optional, is necessary.

**Comment by thomasdavis** [comment]
I love the suggested static values but feel like they might be too presumptuous across different industries.

I would imagine that we as a community/project have unwritten guidelines about what we encourage but not limited to them as such.

Pretty torn on this issue though because uniformity sometimes works incredibly well.

**Comment by aloisdg** [comment]
@stp-ip `JSON` is in english. We have to deal with it. cli/app/template dont have to be english. If someone is a the db aka the json here, he should know a bit of english.

> I love the suggested static values but feel like they might be too presumptuous across different industries.

How so?

> I would imagine that we as a community/project have unwritten guidelines about what we encourage but not limited to them as such.

As a standard, I think we need some guidelines.

**Comment by phumke** [comment]
I'd say stick with the numeric level and push the label out to the visualizer.  Standard naming could still be used and it allows localization.

I'm iffy on unprovided.  If 0 is actually entered into the schema than it has been provided by the user.. It might be a nitpick, but it could be confusing.

**Comment by aloisdg** [comment]
- An int mean's nothing without documentation.
- Enum are awesome for readability.
- Enum allow localization without any kind of trouble.
- Enum are bascially pretty int.

**Comment by phumke** [comment]
@aloisdg Sounds good.  I like the enum, it provides a tightly coupled value and meaning and solves the issue of someone entering 1 and advanced.  I didn't realize enums can be localized.

+1

**Comment by aloisdg** [comment]
@phumke enum are only for the json. The work of the localization should come from the template. But an enum as an obvious meaning even if you read it directly in the json. An enum is just a bunch of int with a pretty name. It is very handy.

**Comment by stp-ip** [comment]
I think we can agree on non numeric enums for the level. But I would still think a label field would make it easier to localize on the data side. I can see, that it could be seen as display information and not data.

**Comment by thomasdavis** [comment]
@aloisdg "Unwritten guidelines" was the wrong phrase sorry.

It my mind it would almost seem like an entirely new project to propose a generic standard for rating competency across the board. In my mind JR would then recommend that standard as a potential value for our own ambiguous property. 

Not that JR couldn't also invent a schema for it and just recommend it. 

Though considering that we do include a rating system the solution above is pretty good. Why does level have to be a string? 

`label` should be included too, it's not necessarily visual and adds a decent amount of flexibility for people across other industries e.g. 

```
skills: [
  {
    name: "Force push",
    level: 3,
    label: "Jedi",
  },
  {
    name: "Force Jump",
    level: 1,
    label: "Apprentice"
  }
]
```

Lots of discussion to be had on this issue, keep the ideas flowing.

**Comment by aloisdg** [comment]
> It my mind it would almost seem like an entirely new project to propose a generic standard for rating competency across the board. In my mind JR would then recommend that standard as a potential value for our own ambiguous property. 

This is an awesome idea! Lets go for it!

> Why does level have to be a string?

Enum can be understand without documentation. It is human compliant and machine readable. An enum is an int, but a pretty one. Since json dont really support enum... Lets go for an ugly int. I still think we should use an enum in our code. I will use one in SharpResume.

Why I dont like label? I am afraid that people will use them in their theme instead of the level. It is a pain to read cv with percentage (68% vs 70% wtf!)  or custom label (rockstar, ninja, wizard, whatever the current hype). The `name` field should be enough to define a context. to the level.

**Comment by stp-ip** [comment]
Proposal:

Documentation:

| int | level | star  | Closing an issue with this skill
| --- | --- | ---  | --- |
| 0 | null | not provided | not provided | not provided | No level was provided
| 1 | beginner | ★☆☆☆☆  | I will teach you how to do it
| 2 | early | ★★☆☆☆ | I will help you to do it
| 3 | competent | ★★★☆☆| I will follow how you do it
| 4 | advanced | ★★★★☆  | I will be there in case of trouble
| 5 | expert | ★★★★★  | I will be there when it is ready

On the implementation side we should use an int (basically representing an enum) from 0-5 with the level as seen above as a basis.

After that first step we could revisit the idea of having a custom label. This enables language levels (aka adds flexibility), but reduces readability etc. quite a lot. Therefore shouldn't go into the first iteration.

**Comment by bussiere** [comment]
+1 for the @stp-ip  suggestion , people can add whatever they want after for the int :)

**Comment by wayneamurphy** [comment]
I like the idea of a(n optional) simple skill level 0-5 or 1-5 that is searchable, but I also like just having a free-form field as well. There are skills I have that I don't want another job doing them, and there are skills I have a little bit on, but I want to really talk those up since that is what I want to focus on in my next job.

**Comment by thomasdavis** [comment]
Closing issues for v1.0.0. 

As much as analytics is desired, it doesn't quite suit the use case of the general users. 

There might have to be a super-format, but for now, the schema suits more the individuals needs.
