### ISSUE TITLE
google analytics tracking

### ISSUE THREAD

**Issue by mudassir0909** [jsonresume/resume-schema#165]
Technically this is not part of the resume data but can we have an optional `meta` attribute where we can specify google analytics tracking code in the json ?

**Comment by mchelen** [comment]
Sounds like a good idea, how about a key:value section for things like Google Analytics, Google Webmaster Tools verification, Bing verification, or even Disqus username if a theme chose to add comments.

**Comment by mudassir0909** [comment]
yep

**Comment by stp-ip** [comment]
+1 for 
"meta": [
  "key": "value",
  "key2": "value2"]
style

**Comment by KOLANICH** [comment]
Maybe we should just remove
>```"additionalProperties": false```

**Comment by olivif** [comment]
@KOLANICH  +1 

what was the original thinking behind not allowing additional properties? I guess it depends a bit how "strict" you want the schema to be.

**Comment by chrisdotcode** [comment]
Metadata will be supported in v1.0.0 that can hold arbitrary key/value pairs (including analytics).

I'm not sure what @KOLANICH was referring to, but I think he might have commented on the wrong issue.

I'm going to close this to reduce issue clutter for now, but if I was incorrect, somebody just re-comment, and I'll re-open.

**Comment by stp-ip** [comment]
I think @KOLANICH was saying that instead of introducing meta-data as a field, he would just open up the structure to allow something similar, just without actually having it in the schema.

I vote for having "additionalProperties": false on the outer borders to have the basic structure the same and introduce a meta-data field to have these things as key, value pairs savely stored in a designated part.

**Comment by chrisdotcode** [comment]
Can you please re-explain `additionalProperties` to me?

**Comment by stp-ip** [comment]
When the schema has ```additionalProperties``` set to false at the highest level no new elements are allowed. So one had to add a custom meta-data section (if wanted) into the personal data part.
With additionalProperties set to true, one could just add meta-data to the outer scope.

**Comment by chrisdotcode** [comment]
Oh, I see what you're saying.

Since we're aiming for machine-readability, I believe that there should only be one true source of truth, the resume schema. Adding an additional properties value means more fragmentation, instead of working as a community towards standardization.

If additionalProperties *are* needed, one can put them in the new metadata field.

**Comment by stp-ip** [comment]
Perfect then we agree and can:
* leave false on the outer scope
* add meta-data section
* close this issue \o/

**Comment by KOLANICH** [comment]
Let it call not metadata, but "arbirtaryData"

**Comment by stp-ip** [comment]
I'm neutral on the naming.

**Comment by chrisdotcode** [comment]
@stp-ip: I'm not in quite agreement. What I was saying, was that the additional properties, if any should go into the metadata section.

additionalProperties seem redundant when we have an arbitrary metadata store.

**Comment by olivif** [comment]
would we even need the additionalProperties flag then?

**Comment by chrisdotcode** [comment]
Right. I was saying we would not. We would just move those additional properties in the metadata field.

**Comment by stp-ip** [comment]
Yeah that's why we have the ```additionalProperties: false``` to no allow additional fields ;)

**Comment by stp-ip** [comment]
additionalProperties is a json schema specific command to prevent additional fields, just to make that clear.

**Comment by chrisdotcode** [comment]
Thank you for that clarification. I thought we were talking about a resumejson schema, not a json schema. Now, I get it, and it sounds good to me.
