### ISSUE TITLE
Work.endDate and education.endDate should not be required

### ISSUE THREAD

**Issue by GuidoBR** [jsonresume/resume-schema#171]
I'm getting the following erros when I run the "resume test"

     ✗ work[0].endDate is  expected 
     ✗ education[0].endDate is  expected 

  fail  2 

It shouldn't be required to provide a end date to work and education.

**Comment by mchelen** [comment]
See https://github.com/jsonresume/resume-cli/issues/60#issuecomment-57051081 for workaround

**Comment by jtwebman** [comment]
What is interesting is the schema file doesn't require any field that I can see.

**Comment by jtwebman** [comment]
Oh nevermind, you can't leave it blank but you don't have to include the field.

**Comment by DandyDev** [comment]
I'm closing this one because it basically duplicates what's already [being](https://github.com/jsonresume/resume-cli/issues/60#issuecomment-57051081) [discussed](https://github.com/jsonresume/resume-cli/issues/54#issuecomment-62068620) [elsewhere](https://github.com/jsonresume/resume-schema/issues/142)
