### ISSUE TITLE
endDate optional

### ISSUE THREAD

**Issue by henkjurriens** [jsonresume/resume-schema#175]
I would like have an optional endDate, for example for my current position

Cheers
Henk

**Comment by luisrudge** [comment]
Yeah. +1 to that

**Comment by jtwebman** [comment]
EndDate isn't required, just remove the field. 

https://github.com/jsonresume/resume-cli/issues/54

**Comment by luisrudge** [comment]
Ok. Thanks!

Enviado pelo meu Windows Phone
________________________________

**Comment by henkjurriens** [comment]
Thanks!

**Comment by DandyDev** [comment]
I'm closing this one because it basically duplicates what's already [being](https://github.com/jsonresume/resume-cli/issues/60#issuecomment-57051081) [discussed](https://github.com/jsonresume/resume-cli/issues/54#issuecomment-62068620) [elsewhere](https://github.com/jsonresume/resume-schema/issues/142)
