### ISSUE TITLE
How to represent present work?

### ISSUE THREAD

**Issue by chrisdotcode** [jsonresume/resume-schema#199]
cf. jsonresume/resume-cli#60

The above is a discussion of how to specify present work. In short, there are three proposed solutions:
- Remove the `endDate` field entirely.
- Make `endDate` null.
- Make `endDate` an empty string.

I'm with the third one, and I definitely _do not_ think that the field should be removed entirely if the work is still ongoing.

Themes can be left to the prettify the empty string.

**Comment by aloisdg** [comment]
I am ok for all of them.

**Comment by devlinjd** [comment]
Some thoughts from an external tool builder supporting JRS.

1. Let `null` and `""` both represent, simply, an unspecified date. Not necessarily "currently working here" and not "some future endDate" but just an unspecified or unknown date. There's no need for the schema itself to specify policy beyond that. IMO that policy belongs at the user, theme, or tool level, not in the baseline schema.

2. Avoid values like `current` or `present` in date fields. This adds a special corner-case to parsing and validation logic, in return for not very much additional utility -- convenience notation should not be driving schema structure especially when it can be handled at the user, theme, or tool level.

3. If the ability to *explicitly* specify the most recent job as "current" is desired, I would take a cue from how most external sites (eg, StackOverflow Careers or Monster) handle this: via a boolean flag on the job record itself. That keeps the date parsing and validation clean and models this with clarity.

4. The "most recent job" is not necessarily always going to be the job the candidate wants to specify as current. Maybe I'm currently working at Veridian Dynamics and have been since 2011, but my most *recent* gig on the resume is a side project for Dunder Mifflin. For cases like this, a boolean flag on the job record seems to make the most sense.

Thanks.

**Comment by stp-ip** [comment]
I would favor the 2 one considering the usual practices with json.

**Comment by chrisdotcode** [comment]
So in #198, @KOLANICH suggests removing the field entirely, and replacing it all with a date array. My addition to that was that we can therefore represent `presentWork` with a boolean if we choose that solution.

Thoughts?

**Comment by stp-ip** [comment]
Would the usage of ```current``` as a boolean be too meaningless? Would in my opinion make everything more consistent, when used for every work, education etc. object.

**Comment by chrisdotcode** [comment]
`presentWork` was just an example. I like `current`.

**Comment by olivif** [comment]
I agree with @stp-ip here, having a flag for things that are on-going could be very useful and applicable to other objects not just education. Use cases I can think of are current jobs, current education, current projects, current publications (you can have the paper written but not published, in which case you might want to mark it as current). Same for things like events you are planning, volunteering work.

**Comment by chrisdotcode** [comment]
We've actually resolved this problem in another thread, #198.

Present work takes cares of itself with the proposed solution.

**Comment by stp-ip** [comment]
@chrisdotcode in most cases yes, but to focus on the bibjson case. They don't have a current/not published state. We could use the year from bibJSON as we would other future dates as discussed in #198, but that needs to be a special thing to look at.

**Comment by chrisdotcode** [comment]
To be frank, if it's not published... it's not published, and therefore shouldn't need to be noted.

As per another suggestion somebody else made in another thread, if we do use bibJSON for publications, we should use that as a black box format in which we follow *their* conventions for their necessary fields.

**Comment by stp-ip** [comment]
@chrisdotcode I agree with the convention and would not add a special string or so, but if their date string is in the future themes should know how to handle that and therefore show "current" most likely.

**Comment by beshur** [comment]
So no decision here?
Should I update endDate every day for the resume to stay valid?

**Comment by aloisdg** [comment]
@beshur It is a long talk. Read more here: #198

**Comment by fartbagxp** [comment]
Mmm, I've been following this problem for about five months now and there hasn't been any resolution yet.

My workaround currently:
Convert the PDF to .docx with Adobe PDF (far superior than other PDF readers in terms of copying and pasting PDF) and appending the "Present" in myself before printing it out or converting it back to PDF.

**Comment by aloisdg** [comment]
> Mmm, I've been following this problem for about five months now and there hasn't been any resolution yet.

Feel free to provide arguments to unlock the situation or a better solution directly. If you have time and motivation to help, it is more than welcome.

**Comment by thomasdavis** [comment]
My vote is for option 2)

Taking types into consideration, an empty string would represent something else. (terrible explanation)

`null` is less verbose because we wouldn't need to repeat redundant properties in each section.

What is the official majority vote at this point, we can probably merge something in.

**Comment by mudassir0909** [comment]
I'm with `null` for representing "present work", upto the themes to ensure they render "Present", "Current" or whatever the label when they encounter `null` in the `endDate`.

**Comment by aloisdg** [comment]
Before arguing about a solution, please read #198 too.

**Comment by alienkidmj12** [comment]
how do we input job history, if i have more than 1 job in there it reports that the current job doesnt have an end date :(

**Comment by noraj** [comment]
Tomorrow we will be in 2019 and we still can't represent a current job.

**Comment by j-ecker** [comment]
We are currently in 2019, has there been any resolution to this?

**Comment by nrgapple** [comment]
has anyone made a fork with *present* integrated?

**Comment by evanplaice** [comment]
A current|present value could be represented by an empty string. For that change to take place #348 will have to be approved and merged first.

**Comment by Velua** [comment]
What happened with this?

**Comment by thomasdavis** [comment]
Most themes have implemented that an `endDate` with the value `null` or simply missing means that you are still at the job.

**Comment by danguilherme** [comment]
> Most themes have implemented that an `endDate` with the value `null` or simply missing means that you are still at the job.

Should the schema change? [The latest one](https://github.com/jsonresume/resume-schema/blob/v1.0.0/schema.json#L449-L451) doesn't allow an empty string or `null` as value.

**Comment by thomasdavis** [comment]
Yeah we should let it be set explicitly to `null` going fourth.
