### ISSUE TITLE
Always allow the user to add additional details in free form

### ISSUE THREAD

**Issue by collimarco** [jsonresume/resume-schema#287]
I don't like CVs that don't allow you to express what you want to say. For example `education` and `skills` should provide a way to add additional details in free form (you can call it `summary` for example).

For example if I want to say that I have received a scholarship for a given education, there's no way to express that - an additional field where you can insert anything would solve all the edge-cases.

**Comment by jjatria** [comment]
Both `education` and `skills` (and most other fields) allow users to input additional fields (as specified in the schema).

So technically, this issue is already solved: you can _already_ add a `summary` field to both `education` and `skills` to add whatever information you want. Since it is not a _standard_ field, you might find that renderers do not take that field into account. But this can be fixed with a custom renderer that looks for those fields.

**Comment by stp-ip** [comment]
The schema is only a base and if really necessary additional fields are allowed as @jjatria already pointed out. Will take the summary idea into consideration for additional sections.
