### ISSUE TITLE
Is project dead?

### ISSUE THREAD

**Issue by asm0dey** [jsonresume/resume-schema#314]
It looks like there is no more activity in this project and version 1.0.0 is still not released. Did you abandon it?

**Comment by stp-ip** [comment]
We are trying to iterate on the schema and tooling over at https://github.com/resumic/schema. Latest schema.json iteration: https://github.com/resumic/schema/blob/master/schema.json

Hopefully this will flow back into jsonresume once we have something in place. Happy for general feedback and ideas here or over at resumic/schema.

**Comment by thomasdavis** [comment]
Only just started getting back into it myself.

Working on a commercial product which leverages JSON Resume so I will be spending more time contributing.

Can check it out at https://jaresume.com

**Comment by fballiano** [comment]
I'm also relying completely on jsonResume' schema for my https://velocv.com/  and it's a little bit scary not to see any update since long time.

I believe that resumes in json format are going to be important in the future and it would be a pity if jsonResume (which is the original project) misses its train and let someone else take the lead.

**Comment by urukalo** [comment]
@thomasdavis please check https://jaresume.com .. it showing heroku page 🙀 
hosting is down too? project is really dead? 😢

**Comment by thomasdavis** [comment]
Bringing them both back up, sorry for the delays.

**Comment by RickCoxDev** [comment]
Still nothing there. I echo others that have commented on this. I would love to this project active again and see new features added.

**Comment by stp-ip** [comment]
There are iterations going on. Unfortunately outside of this repo, but happy for feedback. We are close to where we want the schema.
https://github.com/resumic/schema/blob/master/schema.json
Single source of truth in one Go file.
Theme generation with Hugo has a PoC.
First theme porting WIP.

**Comment by karlitos** [comment]
I would also love to be able to fetch the current Json-resume schema (preferably via NPM) for validation fo my own [CLI tools](https://github.com/karlitos/KissMyResume). Does anyone know where to find the latest Json-resume schema version, so I could at least statically include it for validation ?

**Comment by thomasdavis** [comment]
The registry and theme server have now been revamped -> https://github.com/jsonresume/registry-server/issues/105

**Comment by pke** [comment]
A lot of PR are still open that fix bugs (#331). Are they going to be merged?

I wonder why shaping the schema has been moved outside this project to resumic? Whats the reason behind it? Shouldn't the iterations happen here? Whats with the "Single source of truth in one Go file"? Its just a plain JSON schema. Why would you want to generate that via code?

The idea of a machine readable resume format is nice and in very much need. It could eventually get rid of all the custom job application multi-page forms that job applicants are forced to use today. The format could ease the transition by providing import filters to existing solutions like SAP, SalesForce etc.

The resume registry could be extended to work like gravatar where one just needs to make a link between an email and a resume.

JSON `GET https://jsonresume.org/resume/SHA256`
HTML `GET https://jsonresume.org/resume/SHA256.html?theme=`
QR Code `GET https://jsonresume.org/resume/SHA256.qr`

Many ideas. Sad to see this project stale.

**Comment by stp-ip** [comment]
Resumic was a personal choice of mine (maintainer here as well) to iterate externally as here it was hard to merge something and get going again.
The single source of truth in Go was a design decision to automate a few things from source such as example, schema, bindings etc.

That does not take away from the idea of json schema, but enables other formats as well.

Definitely like the resume registry idea being based on a hash. Would that be a hash of the name or content?
Within resumic we added a meta filed to define a canonical link and a random uuid per resume. The canonical link could be the hosting location such as personal domain etc.

Definitely would love a lot more activity here as well, but tried to at least continue iterating with Resumic. Was it the best solution. Not sure. Does it at least continue the idea. Hopefully.

**Comment by pke** [comment]
The idea is great and thanks for your efforts! :+1: 
Especially during job applications I feel the need to abolish all those proprietary (SAP based *yucks*) solutions with their endless form marathons.
I'd love to integrate JSONSchema with SAP etc. Maybe the big companies won't accept JSONResume because its not XML? ;) 
That's why I also thought a more open spec like "OpenResume" or "OpenVita" would help to get this standardised (OpenCV is taken by intel for its image rec lib). Then we could support JSON and XML together (generated from one source) and maybe find adoption easier in the jurassic enterprise world. I personally like XML because of XPath and XSLT and its possibilities to filter & transform a single source of data.

The hash is from the users email. The idea is similar to gravatar. Imagine a job application form. It asks you for your email and by that alone can pre-populate their job forms or just take the JSONResume point blank and sign you up for the job application.
There are more possibilities I have have outlined [here](https://github.com/jsonresume/registry-functions/issues/3)

That said, it seems the owner of this repo is actively working on the registry-server at the moment so maybe there is a chance to revive it/get more members to gain write access to merge PRs).

**Comment by stp-ip** [comment]
One reason for the Go based source of truth design choice in Resumic was to make json schema just one output, if it makes sense later on. Supporting an xml based output would be possible in that regard.

Ah interesting approach with the gravatar style email. 

Let's hope for a full revival then ;)

**Comment by evanplaice** [comment]
This project is very much not dead. Closing this issue for now.
