### ISSUE TITLE
Courses & Books

### ISSUE THREAD

**Issue by notflip** [jsonresume/resume-schema#316]
It would be nice (as a developer) to show which books and courses you are currently reading/doing.

**Comment by wayneamurphy** [comment]
I would have said that would fall under the education category - but currently that is focused on school learning.
I'm not sure what you mean by "doing" a book? If writing a book then there is a publications section.

Since the current education is focused on school, I would suggest for a new section to relate to other learning (since, for better or worse, fewer people read books these days).
The learning section could relate to books, videos (PluralSight/LinkedInLearning/YouTube/whatever), blogs, Slack chats, ...
Books could include an ISBN, anything could have a URL and a date (for read/last used?), for stuff like PluralSight I suppose it would be particular courses? But you would enumerate what blog entries you read, so I'm not sure about that one.

**Comment by stp-ip** [comment]
Education can mean a school, but it might also be used to add a "school" such as "self-learning" or such. I think this could work.
If one feels it's more a side thing it could be done in the projects section I assume.

**Comment by thomasdavis** [comment]
The JSON Resume ecosystem can't support too many individual preferences. 

I'd suggest that you add a social network for stackoverflow or goodreads.
