### ISSUE TITLE
Issue with start and end date and denoting "ongoing/present". 

### ISSUE THREAD

**Issue by punkscience** [jsonresume/resume-schema#330]
I there should be an additional field called "dateFormat" which would indicate to a tool how to interpret the date -- as a regular date (default) or as a string ("Present", "June, 2017" etc.)

It's very common in Canada to see "July, 2018 - Present" for ongoing jobs. LinkedIn does this too. Tools could/should also be written to interpret the lack of an endDate as "Present".

**Comment by wayneamurphy** [comment]
I'll ask because I think you are talking about 2 different issues.

I agree with the open end date to denote ongoing/present.
(and it should be done for all: work, education, projects, volunteer)

It seems the other relates to a date without a day? Which is listed in item #142 (which I also agree with)
I'm not going to bother actually looking at a calendar to find out what day I actually graduated in the 80s, and it seems there are a number of jobs I started in July - and a fellow Canadian will know I didn't actually start on July 1 :-)

**Comment by eyesno** [comment]
You're right -- it's 2 different issues. Looking back I am not sure why I wrote them in the same issue (which, as you noted is covered in #142. I will go ahead and edit that part out of this.

**Comment by evanplaice** [comment]
Defining a `dateFormat` wouldn't really work with JSON Schema validation as the types are fixed. 

Defining an empty string to indicate 'present' will probably be the best option. It'll be up to template implementors to interpret the empty string and indicate 'present' in whatever form that best integrates with the template.

**Comment by fballiano** [comment]
in all my implementations I've always considered an empty endDate as present/ongoing, just my 2 cents :-)

**Comment by thomasdavis** [comment]
All I can say at this point, is that dates are hard. 

As for common format, I think for now JSON Resume will stick with `iso8601` -> https://github.com/jsonresume/resume-schema/blob/v1.0.0/schema.json
