### ISSUE TITLE
Language skills as special fields

### ISSUE THREAD

**Issue by skade** [jsonresume/resume-schema#34]
Language skills are usually listed independently of normal skills. Also, they follow specialized scales, usually the CEFR or the ILR:

http://en.wikipedia.org/wiki/Common_European_Framework_of_Reference_for_Languages
http://en.wikipedia.org/wiki/Interagency_Language_Roundtable_scale

**Comment by aloisdg** [comment]
I know that this issue is close, but can we think about a move to a spec? I am creating a DB for my team and with the current system I cannot use a basic query to get fluent or higher English speaker. All scale ([ILR](https://en.wikipedia.org/wiki/ILR_scale), [ACTFL](https://en.wikipedia.org/wiki/ACTFL_Proficiency_Guidelines) or [CEFR](https://en.wikipedia.org/wiki/Common_European_Framework_of_Reference_for_Languages)) remove this problem. Also I would love to switch the language to an [ISO 639 format](https://en.wikipedia.org/wiki/ISO_639). I want the data to be accurate as possible.

Think about this issue as a simple problem. Should we use a standard or let the user write a free chaotic string?

I will help you. You already make the good decision. For the date, you choose to follow the standard ISO 8601 and it is perfect. Can we follow your choice of standard for the love of consistency or simplicity?

**Comment by KOLANICH** [comment]
My suggestion moved from #195.
>Add to the specification the results of well-known tests and metrics. To do it
1 make `languages`  an object
2 the key must be a 2 letter language code
3 every language must be an array of metric results, every metric result is an object with fields representing results.
4 for expiring tests the date of pass is required
for example
```json
{
...
 "languages":{
   "en":{
    "CEFR":{
     "listening":"c1",
     "reading":"c1",
     ...
    }
  }
 }
}
```

**Comment by stephen-kruger** [comment]
2-letter language code is not enough. It needs language AND locale :  
e.g. fr_FR ; fr_CA ; es_MX ; es_ES
http://www.i18nguy.com/unicode/language-identifiers.html
