### ISSUE TITLE
How can I add custom items on my resume? Is it possible?

### ISSUE THREAD

**Issue by jeongmincha** [jsonresume/resume-schema#416]
As far as I know, jsonresume supports resume details such as about, work experience, skills, education, awards, etc.
However, I want to add something more than these things. 
I wish there was at least an item called 'Others'.

I tried to add custom items but the parser throws an error. 
Perhaps only some fixed items can be parsed as resume items.

Is this possible? Or did I not find it yet? 
If the current version is impossible to make custom items, could I request this feature? 
I don't need complete customization, I just need an item called 'Others'.

**Comment by jeongmincha** [comment]
@thomasdavis Thanks for your quick reply :)
Is there any documentation for using "meta" property?
Or any examples to refer to?

**Comment by jasonpatrickellykrause** [comment]
@jeongmincha Does this help? https://github.com/jsonresume/resume-schema/issues/204#issuecomment-216636824

I cannot test at the moment.

**Comment by jeongmincha** [comment]
@jasonpatrickellykrause It didn't work :(
Even though I added "whatever" param in "meta" like that comment, but my resume doesn't show anything new.

**Comment by jeongmincha** [comment]
@thomasdavis @jasonpatrickellykrause Thank you for answering my thread, but I didn't solve this problem yet :(
I tried every option that I could imagined, but I couldn't add custom resume fields. Would you please let me know an jsonresume example having custom resume fields?

**Comment by mudassir0909** [comment]
> but my resume doesn't show anything new.

@jeongmincha I think the theme you are using for your resume has to consume that property if a theme isn't doing that then you won't see any changes, does this answer your question?

**Comment by SethFalco** [comment]
Like others have said, this isn't possible right now unless your theme explicitly supports the custom fields you want to add. It's up to theme developers to support the extra fields.

The best way to approach it would be to utilize the `meta` section to include the custom properties you want, then create or fork a theme to utilize them.

While JSON Resume is extensible, not all themes will support that extensibility. If you want whole new sections, that will be difficult to standardize without undermining that JSON Resume is ultimately for résumés. Taking it futher would turn JSON Resume into more of a JSON CMS, at which point you might be better off with Jekyll, Hugo, or a headless CMS solution rather than a JSON Resume theme.

> Is there any documentation for using "meta" property?

There is no documentation for this beyond the JSON Resume schema itself, but that won't help in your case anyway. The proposal was that you define arbitrary data that you can consume in your own theme or a fork of an open-source theme you like.

---

If this something you're still interested in, feel free to respond here or hit me up with a concrete idea of what you want to achieve. I can either help you or do a more detailed write-up of how to approach this. 👍🏽
