### ISSUE TITLE
Position does not allow for array

### ISSUE THREAD

**Issue by johnvilsack** [jsonresume/resume-schema#438]
The current schema locks "position" into an expected string. While uncommon, there are many instances in which a person may have fulfilled multiple roles at the same organization *concurrently* as opposed to chronologically.

For example, I fulfilled the roles of CTO, CIO, and CISO at the same time.

**Comment by virtadpt** [comment]
Same.  Last job I had I was in the roster for three separate positions (engineer, security practitioner, CISO), and before that (system administrator, RF researcher, RF comms consultant).

**Comment by SethFalco** [comment]
Just adding some notes for when/if another maintainer would like to comment/decide on this. 🤔 

I don't know how things work for everyone ofc, but usually people only have 1 job title, unless they actually have multiple jobs/contracts, which isn't often under the same `work` entry.

Having responsibilities for more than 1 role is not the same as a having more than 1 job title which, I think, is what position is referring too.

For example, a full-stack engineer who also does database administration and ticket support still only has 1 position, they just also have other responsibilities which could be noted in `summary` or `highlights`.

Or at least, this is how I would consider it in most cases.

HOWEVER, it does look like there is actually a case to be made for multiple positions or job titles.

> Many employees hold dual (or more) positions simultaneously, and my advice is to list all titles on your resume.
>
> — [Quora](https://www.quora.com/Is-it-okay-to-have-multiple-job-titles-as-your-role-within-a-company-on-your-resume) (Some other responses are similar.)

How practical this is and how most employers view this, I don't know. Giving people the choice to list multiple job titles could be nice though, but at the same time if it's not considered practical, it might be better for this use-case to just be a comma-separated string rather than something that influences the schema.

**Comment by thomasdavis** [comment]
You can just create multiple work items, with your new role, summaries and highlights. 

To keep the schema simple, I think the above is a better strategy then a more complicated nested roles array.
