### ISSUE TITLE
question: about ResumeToPDF

### ISSUE THREAD

**Issue by vikramsoni2** [jsonresume/resume-schema#439]
I just noticed that the ResumeToPDF repo has been archived. How are you guys planning to provide the pdf version of the resume if needed to be printed?

* Can we just use browser print function?
* and add the print specific styles in the theme's css ?

I am curious as I would like to include small autogenerated QR code when you print the resume. Only provide this QR code for print style which points to the registry.jsonresume.org to your resume. What are your thoughts?

**Comment by SethFalco** [comment]
I wasn't around at the time, but I assume it was archived because it wasn't used in this repo.

We can see [here](https://github.com/jsonresume/resume-cli/blob/21d15f6feb58b689abdb0c740b07319cf5fc2133/lib/export-resume.js#L79) that they just run it through a browser and call print.

I haven't tested this, but I'm betting if your theme just used a media query for `print` and set the QR code to visible, it'd work just fine.

More info: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#targeting_media_types

**Comment by vikramsoni2** [comment]
I see the point. Its easier to just use the browser's native print to pdf function. 
About the QR code, my question was not how to add QR code, but more like would you like a pull request to automatically generate and provide qr code for the resumes generated from registry ?

**Comment by nricardo** [comment]
Hi all,

I agree that's easier to just use the print on the browser and save it as PDF, but in reality you get something that's far optimised for the purpose. There's still very little support for CSS Paged Media (@page).
Take a look at https://developer.mozilla.org/en-US/docs/Web/CSS/@page#browser_compatibility and https://caniuse.com/css-paged-media.
That being said, it would be great to have support to create our resume with quality output for PDFs. I had to struggle quite some time to make page breaks work with decent outcome and also keep the background flow when that happens.
BTW: good idea for the QR code... will put that one for sure in my own CV.

**Comment by rvdwegen** [comment]
For anyone interested in this functionality you can also use the HTML to PDF action from fifsky.
https://github.com/marketplace/actions/html-to-pdf
