### ISSUE TITLE
support multiple positions within same job

### ISSUE THREAD

**Issue by mattknox** [jsonresume/resume-schema#51]
ATM, to represent a 5-year stint at a company during which you did many different jobs, you'd need multiple jobs entries.  perhaps it would be best to have positions be an array of objects?

**Comment by mruhlin** [comment]
There is a credible difference between the guy who gets promoted every 2 years and the guy who gets fired or quits every 2 years, so there's a good use case for one entry with a clear startDate and endDate covering the whole stint.
HR *could* merge by company name, but can an applicant rely on that?

**Comment by telekid** [comment]
+1 for supporting multiple positions within a single job rather than relying on duplication of company data. From a data-structure perspective, a position is a natural subcategory of an employer. Asking users to duplicate an employer's information across multiple entries increases the probability of non-uniform data, and makes visually representing positions as a subset of employers difficult and unreliable.

Something like this makes sense to me:

```json
"companies": [{
    "name": "Acme Inc.",
    "website": "www.acme.com",
    "positions": [{
        "location": "New York, NY",
        "corporateTitle": "Vice President",
        "title": "Chip Manufacturing",
        "startDate": "2012-05-03",
        "endDate": "2015-04-30",
        "highlights": [
            "Did something awesome involving math"
        ]
    }]
}]
```

**Comment by JSchwerberg** [comment]
+1 to @telekid 's suggestion.  I think being able to list multiple positions for one company would be beneficial for people who have held many positions at one institution, so that they don't have to waste valuable resume real estate by listing the same company name multiple times.

**Comment by mboudreau** [comment]
@mattknox My opinion on the matter is that data is data, and visualization is another thing.  I see no issues with having different entries for the same company, but if you are to display it, you can always try to find other companies of the same name and display them in a group.

As a developer, I try to use the idea of "make the simple easy and the hard possible".  I think the current schema is more than fine since one person moving within a company, I would imagine, is more of an edge case than the norm (can we get data on this somehow?).

However, I do agree with @thomasdavis around data redundancy and I for one love efficient data.  One way of doing it would be to take an example from [AWS CloudFormation's templating schema](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html) that [uses a 'Ref' object to reference variables/constants](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html).

For example, this is a simple, valid cloudformation template

```
{
	"AWSTemplateFormatVersion": "2010-09-09",
	"Description": "Example Project",
	"Resources": {
		"InstanceProfile": {
			"Type": "AWS::IAM::InstanceProfile",
			"Properties": {
				"Path": "/",
				"Roles": [  "EnterRoleNameHere" ]
			}
		},
        }
}
```

But this is with the knowledge that the role has already been created before using the template and you already know the name.  However, what if you wanted to create the role as part of this template?  This is where the 'Ref' object can be used, like this:

```
{
	"AWSTemplateFormatVersion": "2010-09-09",
	"Description": "Example Project",
	"Resources": {
                "Role": {
			"Type": "AWS::IAM::Role",
			"Properties": {
				"Path": "/"
			}
		},
		"InstanceProfile": {
			"Type": "AWS::IAM::InstanceProfile",
			"Properties": {
				"Path": "/",
				"Roles": [ 
                                        { "Ref": "Role" }
                                ]
			}
		},
        }
}
```

As you can see, the role that was created can be referenced in another entity without the ugly swapping of string names.  Maybe JSON resume can do something similar to this?

```
{
    "work": [
        {
            "company": "Company",
            "position": "President",
            "website": "http://company.com",
            "startDate": "2013-01-01",
            "endDate": "2014-01-01",
            "summary": "Description...",
            "highlights": [ "Started the company" ]
        },
        {
            "company": {"ref": "work[0].company"},
            "position": "President",
            "website": "ref": "work[0].website"},
            "startDate": "2013-01-01",
            "endDate": "2014-01-01",
            "summary": "Description...",
            "highlights": [ "Started the company" ]
        }
    ]
}
```

However, I'm not a fan of using a specific index to reference something in an array.  A better way might be to add a new potential property to add these references like variables:

```
{
    "parameters": {
        "CompanyX": "CompanyX",
        "CompanyXWebsite": "http://companyx.com"
    }
    "work": [
        {
            "company": {"ref": "CompanyX"},
            "position": "President",
            "website": "ref": "CompanyXWebsite"},
            "startDate": "2013-01-01",
            "endDate": "2014-01-01",
            "summary": "Description...",
            "highlights": [ "Started the company" ]
        },
        {
            "company": {"ref": "CompanyX"},
            "position": "Chairman",
            "website": "ref": "CompanyXWebsite"},
            "startDate": "2013-01-01",
            "endDate": "2014-01-01",
            "summary": "Description...",
            "highlights": [ "Started the company" ]
        }
    ]
}
```

Just a thought.  Personally, I think the current way is fine and there's ways around this particular issue.

**Comment by stp-ip** [comment]
I think the current solution would be to have work.projects. So each project has a role assigned to it and can represent an internal role switch or even just a project switch or could be used for client work etc.
We discussed this in more detail in https://github.com/jsonresume/resume-schema/issues/201#issuecomment-157872094.

I think referencing would complicate the tooling around the schema more than necessary, but I agree this should be discussed. I think it's best to discuss the possibility of referencing via variables or otherwise within its own issue. Please open a new issue, with only the referencing and variable idea. The work itself was discussed in the linked issue and in my opinion would work for your use case also.
