### ISSUE TITLE
Get inspiration from Europass

### ISSUE THREAD

**Issue by proier** [jsonresume/resume-schema#60]
http://europass.cedefop.europa.eu/en/about

**Comment by raisty** [comment]
Please, review.
This will be really nice feature.

**Comment by AmauryVanEspen** [comment]
Is this now compatible ? I've added a recent issue here [Europass XML compatibility](https://github.com/jsonresume/resume-schema/issues/490)

**Comment by thomasdavis** [comment]
@AmauryVanEspen over the years I have not seen any converters to make them compatible (maybe one or two but my memory faults me) 

It wouldn't be so hard (in my head), though it would seem there is no such demand. 

From an individual level, I have no such compulsion to work on that, 1. because it is not pragmatic to me and 2. personally when I've looked at europass, it seems rife with bureaucracy, and taking a sledgehammer to a nail approach (albeit a sensible approach to global customs, which is admirable, but I've never steered this project that way (western) (i should add that to the readme))

**Comment by AmauryVanEspen** [comment]
Hi @thomasdavis ,
i've seen you've added the Europass in the Other standards in [resume-schema](https://github.com/jsonresume/resume-schema).
Could you please explain me a bit more why "i wouldn't be so hard (in your head)" =)
As far as i understand, there is already a YAML/Markdown and XML converter.

I would really like to involve in the project, especially with a view to integrate the micro-credentials initiative (competencies approach with badges) into the schema and render.
let me know please how can we plan something here.
Thank you
regards
Amaury
