### ISSUE TITLE
Standard format for phone numbers

### ISSUE THREAD

**Issue by shea256** [jsonresume/resume-schema#69]
Couldn't there be a standard format for phone numbers? I'm just thinking that this could be helpful for any application that enables calling and reads the JSON resumes.

@mwaclawek said: Should definitely be [E.164](https://www.twilio.com/help/faq/phone-numbers/how-do-i-format-phone-numbers-to-work-internationally)

**Comment by mboudreau** [comment]
a lot of places I've seen implement phone numbers as an object with a country code and then the phone number itself.  Whoever ingests the data is the one that needs to figure out how to display it.

We could always have a standard that this object can be used or a string if you want to keep backwards compatibility

**Comment by stp-ip** [comment]
I think for now we are looking into having a standard format of the phone number field in addition to helper tools/libs, which make it easy for theme developers to parse phone data into this standard format. This is just a vague idea and will probably be done post-v1.

**Comment by justinphelps** [comment]
My unsolicited input having work several years in telco and handling phone numbers using the MVC paradigm. 
Views should be able to parse away any various user formatting preferences and reformat into E.164 (without the + since it's redundant and used is an operator/reserved character) for CUD operations before submitting to controller. E.g 0046 (0)76 94-22-2323 becomes 467694222323 when POSTed. Form validators can be flexible, controller/model validators are rigid. 
View formatting for Read operations handled by controller or in js. Sadly there isno phone number formatting in css.  
Models should write phone numbers to the storage layer as string or varchar. It might seem natural to use integers, but that requires longints everywhere. Strings make it easier to index on countrycode/areacode/region and hash. 

Perhaps a solution would be to have *2* optional fields for phone numbers:
"phone": "0046 (0)76 94-22-2323 ", <-- no formatting requirements. Stored however the user wants it presented
"phoneE164": "+467694222323", <-- rigid formatting requirements. Can be used programmatically. Then you could generate <a href="tel:"+467694222323" rel="nofollow">0046 (0)76 94-22-2323</a> without controller or js.
