### ISSUE TITLE
Add section to Education for GPA(international)

### ISSUE THREAD

**Issue by thomasdavis** [jsonresume/resume-schema#7]
As per HN comment

`In the education section, I'd like to see an option for GPA or degree class. Be aware that some countries do not provide a GPA (for example, the UK has these classes: 1st, 2:1, 2:2, 3rd).`

**Comment by GeorgeWL** [comment]
@DandyDev I agree with Free-form string. But why can't we give it a **Name** that works for any country.

GPA is used exclusively in the USA, so people outside the USA often find themselves confused whether they should use it or ignore it.

But giving it a name which makes sense in each system such as `Grade` or `Results` or something akin, that adds more flexibility and reduces chance of confusion. 

The question then becomes, what semantically makes sense as a universal name for the field?

**Comment by stp-ip** [comment]
We are working on a solution, which doesn't rely on people interpreting the grade. Grades have different meaning in various regions and a free form field just pushes the problem to the writer and the reader to associate the same.

**Comment by GeorgeWL** [comment]
JSON schema supports 'switch' tag, you could add 'grade_type' field and require different format based on it using 'switch'

**Comment by DandyDev** [comment]
It's been almost 3 years since my last comment, and I agree with the recent comments that GPA is too specific a name for that field. Something like "Grade" would be better.

Regarding the _value_ of the field, I'm very curious about the solution which doesn't rely on people interpreting the grade. Why is such a solution desirable? What is wrong with people interpreting this thing?

**Comment by GeorgeWL** [comment]
guess if you make it not requiring interpret you could have it possible for non-humans to auto-fill it.

**Comment by stp-ip** [comment]
It enables easier cross region usage, makes the standard more generic and additionally makes it possible to be used by non-humans.

Current idea is to have a percentage scale to store the grade and also call the field "grade" or "score". The interpretation is then moved to a utility function, which makes it easier to provide region specific inputs and outputs and translates them into the generic standard.
A really bare mockup from something similar in the works for skills:
![skills](https://user-images.githubusercontent.com/3768412/29937008-ac9d2faa-8e73-11e7-9872-717fa9b27712.png)

For score and grades it might show the region specific values on the scale or something like that. Suggestions are welcome.

**Comment by GeorgeWL** [comment]
Well, in the EU, self-rating of skills on a scale is seen as conceited and pointless, as we tend to go for descriptive instead,

**Comment by stp-ip** [comment]
As I'm also from the EU I understand this concern. The reasoning:
* machine readable scale
* easy to transform into region specific things
* easily used in addition to other forms such as a description (see vim example)
* workable to input without region specific notions
* no focus on regional specifics within the standard (cause of cross region work, remote work)

Happy to keep discussing. 
We definitely discussed in length the european focus on achievement and not self judgement. That's one of the reasons, why we added the subsection "highlights" to basically showcase what you did instead of just adding less valuable (depends on who you ask) self judged information.

**Comment by DandyDev** [comment]
I know I haven't been involved with the project for a long time, so maybe I'm not in the right place to deliver critiques. But I think what you're proposing @stp-ip, with interpreting grades in utility functions, per region etc., is waaay over-engineered.

This works for json-resume's own utilities/applications, but what about someone writing an application that can import/use resumes described in json-resume, and they write the application in a language other than Javascript? Now they have to rewrite logic...

As far as I'm concerned, there should be little to no interpretation of fields and their datatypes by parsers of the json-resume standard. The notable exception being datetimes, because JSON doesn't natively support those (they'd be expressed as strings).

**Comment by stp-ip** [comment]
Thanks for the critique. How the utility functions actually work is still flexible. Could be that they write to an additional data section or so. 

Adding all regional variances seems like quite a lot of bloat especially considering the various jobs wanting special cases too. We would move from a basic standard, which is extensible to something trying to do everything, but nothing at all.

I appreciate you coming back and contributing with your time.

**Comment by DandyDev** [comment]
No problem! I still hope to see this project succeed and getting a lot of adoption :)

Regarding regional variances: I'm still of mind that we shouldn't deal with those at all. I'd say it is enough to have a field named `grade` with a string as value. Leave to users of the standard to do something with it or not. Especially in light of what I said 3 years ago: although we want to support adding grades to your eduction, we don't want to encourage that as a widely used selection criterium. But that's my opinion ;)

**Comment by stp-ip** [comment]
Will definitely take that all into consideration. Hope it's ok to ping you, when we have a first draft of our overhaul.

**Comment by DandyDev** [comment]
Sure! Looking forward to it!
